### ISSUE TITLE
Stylus Support ?

### ISSUE THREAD

**Issue by mehrdd** [awjudd/l4-assetprocessor#2]
Hi,
Is there any support for Stylus CSS Preprocessor ?

thanks.

**Comment by awjudd** [comment]
There is currently no support for it.  However, if there is a good PHP preprocessor for it that is open source, it should be fairly easy to add.

**Comment by mehrdd** [comment]
Yes, there is : https://github.com/AustP/Stylus.php
thanks.

**Comment by awjudd** [comment]
@mehrdd I was starting to look into Stylus and I found out that it is fairly dynamic and basically requires PHP to be run on top of it which doesn't really flow with the rest of the asset processor.  It mostly works with static files.
